# Generated by Django 5.2.6 on 2025-09-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Lương thực nhận sau khi bị trừ', max_digits=12),
        ),
    ]
