# Generated by Django 5.2.6 on 2025-09-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0002_remove_leavetype_days_allowed_leavetype_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
