# Generated by Django 5.2.6 on 2025-09-23 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0003_remove_performancescore_criterion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performance',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='performance',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('finalized', 'Finalized')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='performance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='hrms.employee'),
        ),
    ]
