# Generated by Django 5.2.6 on 2025-09-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0003_alter_leavetype_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='annual_leave_remaining',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20),
        ),
    ]
