# Generated by Django 5.2.6 on 2025-09-30 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0004_alter_performance_options_performance_status_and_more'),
        ('hrms', '0004_employee_annual_leave_remaining_and_more'),
    ]

    operations = [
    ]
