# Generated by Django 5.2.6 on 2025-10-01 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0002_employee_net_salary'),
        ('hrms', '0005_merge_20250930_1408'),
    ]

    operations = [
    ]
