# Generated by Django 5.2.6 on 2025-10-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0006_alter_leaverequest_status_alter_performance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='overall_rating',
            field=models.FloatField(),
        ),
    ]
