# Generated by Django 5.2.6 on 2025-10-01 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0006_alter_leaverequest_status_alter_performance_status'),
        ('hrms', '0007_alter_leaverequest_status_alter_performance_status'),
    ]

    operations = [
    ]
