# Generated by Django 5.2.6 on 2025-10-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0007_alter_performance_overall_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='overall_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
