# Generated by Django 5.2.6 on 2025-10-01 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0008_merge_20251001_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_percent', models.DecimalField(decimal_places=2, help_text='Phần trăm phạt lương khi nghỉ loại này (VD: 50.00 cho 50%)', max_digits=5)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='hrms.leavetype')),
            ],
        ),
    ]
