# Generated by Django 5.2.6 on 2025-10-02 07:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0009_leavepenalty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AddField(
            model_name='attendance',
            name='break_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='break_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='early_departure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='expected_end',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='expected_start',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='late_arrival',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='location',
            field=models.CharField(blank=True, help_text='IP address or location info', max_length=255),
        ),
        migrations.AddField(
            model_name='attendance',
            name='overtime_hours',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('checked_in', 'Checked In'), ('on_break', 'On Break'), ('checked_out', 'Checked Out'), ('incomplete', 'Incomplete')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_in',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
