# Generated by Django 5.2.6 on 2025-10-02 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0010_alter_attendance_options_attendance_break_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='expected_end',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='expected_start',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
