# Generated by Django 5.2.6 on 2025-10-02 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0011_alter_attendance_expected_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='leave_request',
            field=models.ForeignKey(blank=True, help_text='Associated leave request if on leave', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrms.leaverequest'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('checked_in', 'Checked In'), ('on_break', 'On Break'), ('checked_out', 'Checked Out'), ('incomplete', 'Incomplete'), ('on_leave', 'On Leave')], default='not_started', max_length=20),
        ),
    ]
