# Generated by Django 5.2.6 on 2025-10-02 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0012_attendance_leave_request_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='break_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
