# Generated by Django 5.2.6 on 2025-10-03 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0002_employee_net_salary'),
        ('hrms', '0008_alter_performance_overall_rating'),
        ('hrms', '0013_alter_attendance_break_duration'),
    ]

    operations = [
    ]
