# Generated by Django 5.2.6 on 2025-10-04 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0006_alter_attendance_break_duration_and_more'),
        ('hrms', '0013_alter_attendance_break_duration'),
    ]

    operations = [
    ]
