# Generated by Django 5.2.6 on 2025-10-04 01:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0014_merge_20251004_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='break_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
