# Generated by Django 5.2.6 on 2025-10-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrecord',
            name='absent_days',
            field=models.IntegerField(default=0, help_text='Number of absent days'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='incomplete_days',
            field=models.IntegerField(default=0, help_text='Number of incomplete attendance days'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='late_days',
            field=models.IntegerField(default=0, help_text='Number of late arrival days'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Overtime hours this month', max_digits=6),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='total_hours_worked',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total hours worked this month', max_digits=6),
        ),
    ]
